[2025-05-24T22:32:02.332+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T22:32:02.404+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.upload_merged_to_s3 manual__2025-05-24T21:29:11.201967+00:00 [queued]>
[2025-05-24T22:32:02.486+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supplier_data_etl_pipeline.upload_merged_to_s3 manual__2025-05-24T21:29:11.201967+00:00 [queued]>
[2025-05-24T22:32:02.489+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 8
[2025-05-24T22:32:02.527+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_merged_to_s3> on 2025-05-24 21:29:11.201967+00:00
[2025-05-24T22:32:02.547+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1821) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-24T22:32:02.553+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'supplier_data_etl_pipeline', 'upload_merged_to_s3', 'manual__2025-05-24T21:29:11.201967+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/supplier_dag.py', '--cfg-path', '/tmp/tmp1n7p38af']
[2025-05-24T22:32:02.555+0000] {standard_task_runner.py:63} INFO - Started process 1830 to run task
[2025-05-24T22:32:02.555+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask upload_merged_to_s3
[2025-05-24T22:32:02.744+0000] {task_command.py:426} INFO - Running <TaskInstance: supplier_data_etl_pipeline.upload_merged_to_s3 manual__2025-05-24T21:29:11.201967+00:00 [running]> on host a7d211f7b093
[2025-05-24T22:32:03.237+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supplier_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='upload_merged_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T21:29:11.201967+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T21:29:11.201967+00:00'
[2025-05-24T22:32:03.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T22:32:05.697+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-24T22:32:05.702+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T22:32:05.798+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=supplier_data_etl_pipeline, task_id=upload_merged_to_s3, execution_date=20250524T212911, start_date=20250524T223202, end_date=20250524T223205
[2025-05-24T22:32:05.858+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-24T22:32:06.001+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T22:32:06.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
